# Generated by Django 5.1 on 2024-08-29 19:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('Discription', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Tasks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=100)),
                ('Discription', models.TextField()),
                ('Deadline', models.DateTimeField()),
                ('Status', models.CharField(choices=[('Done', 'Done'), ('In Progress', 'In Progress'), ('Not Started', 'Not Started')], max_length=50)),
                ('Category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.categories')),
            ],
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Discription', models.TextField()),
                ('CreationDate', models.DateTimeField(auto_now_add=True)),
                ('Task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.tasks')),
            ],
        ),
    ]
